package app

import (
	"io"
	"net/http"
)

const serverAcceptancePageHTML = `<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Server 执行验收</title>
<style>
:root{font-family:Inter,"Microsoft YaHei",sans-serif;color:#e8edf7;background:#0b1020}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at top,#17213d,#0b1020 48%);min-height:100vh}.shell{max-width:1420px;margin:auto;padding:30px}.head,.card{background:rgba(20,29,52,.9);border:1px solid #2d3a5d;border-radius:17px;box-shadow:0 20px 70px #02050c66}.head{padding:24px;display:flex;justify-content:space-between;gap:20px;align-items:center}.head h1{margin:0 0 7px;font-size:28px}.muted,.head p{margin:0;color:#aebad4;line-height:1.65}.notice{margin:17px 0;padding:14px 18px;border:1px solid #815f25;background:#2d2415;color:#ffda8a;border-radius:12px}.tabs,.actions,.filters,.checks,.artifacts{display:flex;gap:9px;align-items:center;flex-wrap:wrap}button,.link{border:0;border-radius:9px;padding:11px 16px;font-size:14px;font-weight:700;background:#72a5ff;color:#081126;cursor:pointer;text-decoration:none}button.secondary{background:#27344f;color:#dbe6fa}button.active{background:#e8edf7;color:#111a2d}button:disabled{opacity:.45;cursor:wait}input{min-width:270px;border:1px solid #3a496e;border-radius:9px;background:#0d1427;color:#eef4ff;padding:11px 13px;font-size:14px}.toolbar{display:flex;justify-content:space-between;gap:14px;margin:16px 0}.summary{display:grid;grid-template-columns:repeat(4,1fr);gap:13px;margin:16px 0}.metric{padding:17px}.metric span{display:block;color:#91a0bd;font-size:13px}.metric strong{display:block;margin-top:7px;font-size:21px}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:15px}.scenario,.package{padding:19px}.row{display:flex;justify-content:space-between;gap:12px;align-items:start}.scenario h2,.package h2{font-size:17px;margin:0;overflow-wrap:anywhere}.pill,.check,.tag{font-size:12px;border-radius:999px;padding:5px 9px;background:#27344f;white-space:nowrap}.ok{color:#78e0b6}.pill.ok{background:#143c31}.fail{color:#ff9aaa}.pill.fail{background:#4b2029}.warn{color:#ffda8a}.pill.warn{background:#453719}.scenario p,.package p{color:#b3bfd6;line-height:1.6}.check{border-radius:7px}.repair,.detail,.issue{margin-top:13px;padding:12px;background:#0d1427;border-radius:9px;border:1px solid #283551}.repair code,.mono{color:#a9c8ff;overflow-wrap:anywhere}.issue{border-color:#62432e}.issue b{color:#ffca75}.sections{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:11px;margin-top:13px}.sections h3{margin:0 0 9px;font-size:14px}.line{padding:8px 0;border-top:1px solid #24304a;color:#bec9dc;font-size:13px;line-height:1.5}.line:first-of-type{border:0}.hidden{display:none!important}.empty{text-align:center;padding:55px;color:#9cabc6}.error{color:#ff9aaa;margin:10px 0}.full{grid-column:1/-1}@media(max-width:900px){.summary,.grid,.sections{grid-template-columns:1fr}.head,.toolbar{align-items:start;flex-direction:column}.shell{padding:18px}}
</style></head><body><main class="shell">
<section class="head"><div><h1>Server 执行验收</h1><p>分别查看 Server 固定回归能力和真实 App → Exchange → Server 联调证据。</p></div><div class="tabs"><button id="fixedTab" class="secondary active">Server 固定验收</button><button id="realTab" class="secondary">真实 App 包验收</button></div></section>
<div id="fixedPane"><div class="notice">这是 Server 本地受控验收，不使用用户数据或生产凭据，不能作为真实 App → Server 联调通过依据。</div><div class="toolbar"><div></div><div class="actions"><button id="refreshFixed" class="secondary">刷新结果</button><button id="runFixed">运行完整验收</button></div></div><section class="summary"><div class="card metric"><span>验收类型</span><strong>Server 固定包</strong></div><div class="card metric"><span>运行时</span><strong id="runtime">-</strong></div><div class="card metric"><span>严格门禁</span><strong id="gate">-</strong></div><div class="card metric"><span>场景数量</span><strong id="count">0</strong></div></section><div id="fixedError" class="error"></div><section id="scenarios" class="grid"><div class="card empty full">正在读取最近一次验收结果...</div></section></div>
<div id="realPane" class="hidden"><div class="notice">只有经过 Installation 会话认证、运行时为 browser-agent-outline-v1 且严格证据完整的结果，才算真实 App 联调通过。自报来源和 Server 固定包均不计入。</div><div class="toolbar"><div class="filters"><input id="orgID" placeholder="输入 X-Cascade-Org-ID，例如 org_local_test"><button id="loadReal">读取真实包</button></div><div class="actions"><button id="refreshReal" class="secondary">刷新状态</button></div></div><div id="realError" class="error"></div><section id="packages" class="grid"><div class="card empty full">输入组织编号后读取正式 Exchange 中的执行包。</div></section></div>
</main><script>
const byId=(id)=>document.getElementById(id);const esc=(v)=>String(v??'').replace(/[&<>"']/g,(c)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function bridgeData(payload){if(!payload.ok)throw new Error(payload.error||'请求失败');return payload.data||{}}
function setTab(real){byId('fixedPane').classList.toggle('hidden',real);byId('realPane').classList.toggle('hidden',!real);byId('fixedTab').classList.toggle('active',!real);byId('realTab').classList.toggle('active',real)}
function repairHTML(a){if(!a)return '';return '<div class="repair"><b>受限修复审计</b><p>字段：<code>'+esc(a.field)+'</code><br>修改：<code>'+esc(a.before||'空')+'</code> → <code>'+esc(a.after)+'</code><br>策略：'+esc(a.policy_decision)+' · 第 '+esc(a.attempt)+' 次 · 原包哈希'+(a.approved_bundle_hash_intact?'保持不变':'异常')+'</p></div>'}
function scenarioHTML(s){const checks=(s.assertions||[]).map((c)=>'<span class="check '+(c.passed?'ok':'fail')+'">'+esc(c.kind)+' · '+(c.passed?'通过':'失败')+'</span>').join('');return '<article class="card scenario"><div class="row"><h2>'+esc(s.description)+'</h2><span class="pill '+(s.verdict==='passed'?'ok':'fail')+'">'+(s.verdict==='passed'?'通过':'失败')+'</span></div><p><b>预期：</b>'+esc(s.expected)+'<br><b>实际：</b>'+esc(s.actual)+'</p><div class="checks">'+checks+'</div>'+repairHTML(s.repair_audit)+'</article>'}
function renderFixed(view){const r=view.report;byId('runtime').textContent=r?.runtime||'未运行';byId('gate').textContent=r?.strict_gate==='passed'?'通过':'未通过';byId('count').textContent=String(r?.scenarios?.length||0);byId('scenarios').innerHTML=r?.scenarios?.length?r.scenarios.map(scenarioHTML).join(''):'<div class="card empty full">'+esc(view.message||'尚未运行验收')+'</div>'}
async function loadFixed(run=false){byId('fixedError').textContent='';byId('runFixed').disabled=run;try{const res=await fetch(run?'/v1/desktop/browser-agent-acceptance/run':'/v1/desktop/browser-agent-acceptance',{method:run?'POST':'GET'});renderFixed(bridgeData(await res.json()))}catch(e){byId('fixedError').textContent=String(e.message||e)}finally{byId('runFixed').disabled=false}}
function issueHTML(i){return '<div class="issue"><b>'+esc(i.code)+' · '+esc(i.owner==='app'?'App 负责':'Server 负责')+'</b><div class="line">字段：<span class="mono">'+esc(i.field||'-')+'</span><br>'+esc(i.message)+'<br>建议：'+esc(i.action)+'</div></div>'}
function lines(title,items,fn){return '<div class="detail"><h3>'+esc(title)+'（'+items.length+'）</h3>'+(items.length?items.map(fn).join(''):'<div class="line">暂无</div>')+'</div>'}
function resultHTML(p){const r=p.result;if(!r)return '';const steps=lines('StepResult',r.steps||[],x=>'<div class="line"><b>'+esc(x.node_id)+'</b> · '+esc(x.status)+' · '+(x.observed?'真实观察':'非真实观察')+' · 验证 '+esc(x.validation_count)+'</div>');const vals=lines('Validation',r.validations||[],x=>'<div class="line">'+esc(x.phase)+' · '+esc(x.node_id||'全局')+' · '+esc(x.decision)+' · 通过率 '+esc(x.pass_rate)+'</div>');const events=lines('阶段事件',r.stage_events||[],x=>'<div class="line">#'+esc(x.sequence)+' '+esc(x.stage_id)+' · '+esc(x.event_type)+' · 尝试 '+esc(x.attempt)+'</div>');const patches=lines('补丁账本',r.patches||[],x=>'<div class="line">'+esc(x.field)+'：'+esc(x.before||'空')+' → '+esc(x.after)+' · '+(x.applied?'已应用':'已拒绝')+'</div>');const arts=lines('产物',r.artifacts||[],x=>'<div class="line"><b>'+esc(x.kind)+'</b> · '+esc(x.mime_type||'-')+' · '+esc(x.size_bytes)+' bytes '+(x.download_url?'<a class="link" href="'+esc(x.download_url)+'">下载</a>':'')+'</div>');return '<div class="sections full">'+steps+vals+events+patches+arts+'</div>'}
function packageHTML(p){const a=p.status?.result_summary?.acceptance||p.result?.acceptance;const verified=p.source?.origin==='app_formal_exchange'&&p.source?.transport_authenticated;const state=a?.status||p.eligibility?.verdict||p.status?.status;const tone=state==='ready_for_app_e2e_acceptance'?'ok':(state==='blocked'||state==='failed'||state==='unverified_origin'?'fail':'warn');const issues=(p.eligibility?.issues||[]).map(issueHTML).join('');const run=p.eligibility?.can_run?'<button class="run-real" data-id="'+esc(p.exchange_package_id)+'">运行此真实包</button>':'';return '<article class="card package full"><div class="row"><div><h2>'+esc(p.package_id||p.exchange_package_id)+'</h2><p class="mono">'+esc(p.exchange_package_id)+'</p></div><span class="pill '+tone+'">'+esc(state)+'</span></div><div class="checks"><span class="check '+(verified?'ok':'fail')+'">来源：'+esc(p.source?.origin)+'</span><span class="check">状态：'+esc(p.status?.status)+'</span><span class="check">阶段：'+esc(p.status?.stage||'-')+'</span><span class="check">进度：'+esc(p.status?.progress_percent||0)+'%</span><span class="check">步骤：'+esc(p.package?.script_step_count||0)+'</span></div>'+issues+'<div class="actions" style="margin-top:13px">'+run+'</div>'+resultHTML(p)+'</article>'}
let realRefreshTimer;async function loadReal(){const org=byId('orgID').value.trim();if(!org){byId('realError').textContent='请先填写组织编号。';return}localStorage.setItem('cascadeAcceptanceOrg',org);byId('realError').textContent='';clearTimeout(realRefreshTimer);try{const res=await fetch('/v1/desktop/app-execution-acceptance?org_id='+encodeURIComponent(org));const view=bridgeData(await res.json());byId('packages').innerHTML=view.items?.length?view.items.map(packageHTML).join(''):'<div class="card empty full">当前组织还没有真实 App 上传的执行包。</div>';if((view.items||[]).some(x=>['queued','running'].includes(x.status?.status)))realRefreshTimer=setTimeout(loadReal,1500)}catch(e){byId('realError').textContent=String(e.message||e)}}
async function runReal(id){const org=byId('orgID').value.trim();byId('realError').textContent='';try{const res=await fetch('/v1/desktop/app-execution-acceptance/'+encodeURIComponent(id)+'/run?org_id='+encodeURIComponent(org),{method:'POST'});bridgeData(await res.json());await loadReal()}catch(e){byId('realError').textContent=String(e.message||e)}}
byId('fixedTab').onclick=()=>setTab(false);byId('realTab').onclick=()=>setTab(true);byId('refreshFixed').onclick=()=>loadFixed(false);byId('runFixed').onclick=()=>loadFixed(true);byId('loadReal').onclick=loadReal;byId('refreshReal').onclick=loadReal;byId('packages').onclick=(e)=>{const b=e.target.closest('.run-real');if(b)runReal(b.dataset.id)};byId('orgID').value=localStorage.getItem('cascadeAcceptanceOrg')||'';loadFixed(false);
</script></body></html>`

func (s *DevHTTPServer) handleServerAcceptancePage(w http.ResponseWriter, r *http.Request) {
	if err := s.requireLocalServerAcceptance(r); err != nil {
		http.Error(w, err.Error(), http.StatusForbidden)
		return
	}
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	w.Header().Set("Cache-Control", "no-store")
	w.Header().Set("X-Content-Type-Options", "nosniff")
	w.Header().Set("Content-Security-Policy", "default-src 'self'; style-src 'unsafe-inline'; script-src 'unsafe-inline'; connect-src 'self'; img-src 'self' data:; media-src 'self'")
	_, _ = io.WriteString(w, serverAcceptancePageHTML)
}
