package agents

import (
	"encoding/json"
	"errors"
	"fmt"
	"strconv"
	"strings"

	"cascade-demoops/backend/internal/model"
)

const (
	scriptCodeGeneratorName    = "cascade_deterministic_script_code_generator"
	scriptCodeGeneratorVersion = "0.1.0"
)

type ScriptCodeGenerator struct{}

func NewScriptCodeGenerator() *ScriptCodeGenerator { return &ScriptCodeGenerator{} }

func (g *ScriptCodeGenerator) Generate(doc *model.ExecutionScriptDocument) (string, error) {
	if doc == nil {
		return "", errors.New("execution script document is required")
	}
	if len(doc.Steps) == 0 {
		return "", errors.New("execution script document must contain steps")
	}
	planHash := doc.Reproducibility.ScriptHashSHA256
	if planHash == "" {
		hash, err := doc.ComputeScriptHash()
		if err != nil {
			return "", err
		}
		planHash = hash
	}

	var builder strings.Builder
	writeScriptPrelude(&builder, doc, planHash)
	for _, step := range doc.Steps {
		if err := writeScriptStep(&builder, doc, step); err != nil {
			return "", err
		}
	}
	builder.WriteString("  await ctx.capture.stop();\n")
	builder.WriteString("  return { ok: true, planHash: cascadePlanHash, stepResults };\n")
	builder.WriteString("}\n")
	return builder.String(), nil
}

func writeScriptPrelude(builder *strings.Builder, doc *model.ExecutionScriptDocument, planHash string) {
	nodeIDs := make([]string, 0, len(doc.Steps))
	for _, step := range doc.Steps {
		nodeIDs = append(nodeIDs, step.NodeID)
	}
	redactions := uniqueStrings(append([]string{}, doc.SafetyPolicy.Redactions.MaskSelectors...))
	builder.WriteString("// Generated by Cascade DemoOps. Do not edit manually; regenerate from ExecutionScriptDocument.\n")
	builder.WriteString("// The cloud worker must validate this file against its JSON plan before sandbox execution.\n")
	builder.WriteString("type CascadeStepResult = { nodeId: string; status: \"passed\" | \"failed\"; durationMs?: number; error?: string };\n")
	builder.WriteString("type CascadeRecordingResult = { ok: boolean; planHash: string; stepResults: CascadeStepResult[] };\n")
	builder.WriteString("type CascadePage = {\n")
	builder.WriteString("  goto(url: string, options?: Record<string, unknown>): Promise<void>;\n")
	builder.WriteString("  click(selector: string, options?: Record<string, unknown>): Promise<void>;\n")
	builder.WriteString("  fill(selector: string, value: string, options?: Record<string, unknown>): Promise<void>;\n")
	builder.WriteString("  selectOption(selector: string, value: string, options?: Record<string, unknown>): Promise<void>;\n")
	builder.WriteString("  setInputFiles(selector: string, files: string | string[]): Promise<void>;\n")
	builder.WriteString("  waitForTimeout(milliseconds: number): Promise<void>;\n")
	builder.WriteString("  waitForLoadState(state?: string, options?: Record<string, unknown>): Promise<void>;\n")
	builder.WriteString("  locator(selector: string): { waitFor(options?: Record<string, unknown>): Promise<void> };\n")
	builder.WriteString("};\n")
	builder.WriteString("type CascadeSecrets = { get(secretRef: string): Promise<string>; getInput(inputRef: string): Promise<string>; getFile(ref: string): Promise<string | string[]> };\n")
	builder.WriteString("type CascadeCapture = { start(metadata?: Record<string, unknown>): Promise<void>; stop(): Promise<void>; mark(nodeId: string, metadata?: Record<string, unknown>): Promise<void>; screenshot(options?: Record<string, unknown>): Promise<void>; applyRedactions(selectors: string[]): Promise<void> };\n")
	builder.WriteString("type CascadeAssert = { step(nodeId: string, expected: string, options?: Record<string, unknown>): Promise<void>; visible(selector: string, options?: Record<string, unknown>): Promise<void>; text(selector: string, expected: string, options?: Record<string, unknown>): Promise<void>; url(url: string, options?: Record<string, unknown>): Promise<void>; apiCall(nodeId: string, options?: Record<string, unknown>): Promise<void> };\n")
	builder.WriteString("type CascadeLog = { step(nodeId: string, title: string): Promise<void>; info(message: string, metadata?: Record<string, unknown>): Promise<void> };\n")
	builder.WriteString("type CascadeRecordingContext = { page: CascadePage; secrets: CascadeSecrets; capture: CascadeCapture; assert: CascadeAssert; log: CascadeLog };\n\n")
	builder.WriteString("const cascadePlanHash = " + jsString(planHash) + ";\n")
	builder.WriteString("const cascadeNodeIds = " + jsJSON(nodeIDs) + ";\n")
	builder.WriteString("const cascadeAllowedDomains = " + jsJSON(doc.SafetyPolicy.AllowedDomains) + ";\n")
	builder.WriteString("const cascadeForbiddenPages = " + jsJSON(doc.SafetyPolicy.ForbiddenPages) + ";\n")
	builder.WriteString("const cascadeRedactionSelectors = " + jsJSON(redactions) + ";\n\n")
	usernameRef, passwordRef := demoCredentialSecretRefs(doc)
	builder.WriteString("const cascadeBaseURL = " + jsString(doc.RecordingRunSpec.BaseURL) + ";\n")
	builder.WriteString("const cascadeDemoUsernameSecretRef = " + jsString(usernameRef) + ";\n")
	builder.WriteString("const cascadeDemoPasswordSecretRef = " + jsString(passwordRef) + ";\n")
	builder.WriteString("let cascadeLoginAttempted = false;\n\n")
	writeScriptRuntimeHelpers(builder)
	builder.WriteString("export async function runCascadeRecording(ctx: CascadeRecordingContext): Promise<CascadeRecordingResult> {\n")
	builder.WriteString("  const stepResults: CascadeStepResult[] = [];\n")
	builder.WriteString("  await ctx.capture.start({ planHash: cascadePlanHash, nodeIds: cascadeNodeIds, allowedDomains: cascadeAllowedDomains, forbiddenPages: cascadeForbiddenPages });\n")
	builder.WriteString("  await ctx.capture.applyRedactions(cascadeRedactionSelectors);\n")
}

func writeScriptRuntimeHelpers(builder *strings.Builder) {
	builder.WriteString("async function cascadeResolveSelector(ctx: CascadeRecordingContext, nodeId: string, candidates: string[], timeoutMs: number): Promise<string> {\n")
	builder.WriteString("  const unique = Array.from(new Set(candidates.map((item) => item.trim()).filter(Boolean)));\n")
	builder.WriteString("  const perCandidateTimeout = Math.max(700, Math.min(2500, Math.floor(timeoutMs / Math.max(unique.length, 1))));\n")
	builder.WriteString("  for (const selector of unique) {\n")
	builder.WriteString("    const found = await ctx.page.locator(selector).waitFor({ state: \"visible\", timeout: perCandidateTimeout }).then(() => true).catch(() => false);\n")
	builder.WriteString("    if (found) {\n")
	builder.WriteString("      await ctx.log.info(\"adaptive selector resolved\", { nodeId, selector });\n")
	builder.WriteString("      return selector;\n")
	builder.WriteString("    }\n")
	builder.WriteString("  }\n")
	builder.WriteString("  throw new Error(\"adaptive selector not found for \" + nodeId + \": \" + unique.join(\" | \"));\n")
	builder.WriteString("}\n\n")
	builder.WriteString("async function cascadeTryClick(ctx: CascadeRecordingContext, nodeId: string, candidates: string[], timeoutMs: number): Promise<boolean> {\n")
	builder.WriteString("  const selector = await cascadeResolveSelector(ctx, nodeId, candidates, timeoutMs).catch(() => \"\");\n")
	builder.WriteString("  if (!selector) return false;\n")
	builder.WriteString("  await ctx.page.click(selector, { timeout: timeoutMs }).catch(() => undefined);\n")
	builder.WriteString("  await ctx.page.waitForLoadState(\"networkidle\", { timeout: Math.min(timeoutMs, 6000) }).catch(() => undefined);\n")
	builder.WriteString("  return true;\n")
	builder.WriteString("}\n\n")
	builder.WriteString("async function cascadeEnsureDemoLogin(ctx: CascadeRecordingContext): Promise<void> {\n")
	builder.WriteString("  if (cascadeLoginAttempted || !cascadeDemoUsernameSecretRef || !cascadeDemoPasswordSecretRef) return;\n")
	builder.WriteString("  cascadeLoginAttempted = true;\n")
	builder.WriteString("  const usernameSelectors = [\"input[type='email']\", \"input[name='email']\", \"input[name='username']\", \"input[name='account']\", \"input[autocomplete='username']\", \"input[autocomplete='email']\", \"input[id*='email' i]\", \"input[id*='user' i]\", \"input[type='text']\"];\n")
	builder.WriteString("  const passwordSelectors = [\"input[type='password']\", \"input[name='password']\", \"input[id*='password' i]\", \"input[autocomplete='current-password']\"];\n")
	builder.WriteString("  const submitSelectors = [\"button[type='submit']\", \"input[type='submit']\", \"button:has-text('登录')\", \"button:has-text('登陆')\", \"button:has-text('Sign in')\", \"button:has-text('Login')\", \"[role='button']:has-text('登录')\", \"[role='button']:has-text('Sign in')\"];\n")
	builder.WriteString("  const triggerSelectors = [\"a:has-text('登录')\", \"a:has-text('控制台')\", \"a:has-text('Console')\", \"a:has-text('Dashboard')\", \"a:has-text('Sign in')\", \"a:has-text('Login')\", \"button:has-text('登录')\", \"button:has-text('Sign in')\", \"a[href*='login']\", \"a[href*='signin']\", \"a[href*='sign-in']\", \"a[href*='dashboard']\", \"a[href*='console']\"];\n")
	builder.WriteString("  let passwordSelector = await cascadeResolveSelector(ctx, \"login_password_probe\", passwordSelectors, 1400).catch(() => \"\");\n")
	builder.WriteString("  if (!passwordSelector) {\n")
	builder.WriteString("    await cascadeTryClick(ctx, \"login_trigger\", triggerSelectors, 2500);\n")
	builder.WriteString("    passwordSelector = await cascadeResolveSelector(ctx, \"login_password_after_trigger\", passwordSelectors, 2500).catch(() => \"\");\n")
	builder.WriteString("  }\n")
	builder.WriteString("  if (!passwordSelector && cascadeBaseURL) {\n")
	builder.WriteString("    for (const path of [\"/login\", \"/signin\", \"/sign-in\", \"/auth/login\", \"/app/login\", \"/dashboard\", \"/console\"]) {\n")
	builder.WriteString("      await ctx.page.goto(new URL(path, cascadeBaseURL).toString(), { waitUntil: \"domcontentloaded\", timeout: 6000 }).catch(() => undefined);\n")
	builder.WriteString("      await ctx.page.waitForLoadState(\"networkidle\", { timeout: 5000 }).catch(() => undefined);\n")
	builder.WriteString("      passwordSelector = await cascadeResolveSelector(ctx, \"login_password_path\" + path, passwordSelectors, 1600).catch(() => \"\");\n")
	builder.WriteString("      if (passwordSelector) break;\n")
	builder.WriteString("    }\n")
	builder.WriteString("  }\n")
	builder.WriteString("  if (!passwordSelector) {\n")
	builder.WriteString("    await ctx.log.info(\"demo login form not found; continuing with adaptive business discovery\", { nodeId: \"login\" });\n")
	builder.WriteString("    return;\n")
	builder.WriteString("  }\n")
	builder.WriteString("  const usernameSelector = await cascadeResolveSelector(ctx, \"login_username\", usernameSelectors, 2500).catch(() => \"\");\n")
	builder.WriteString("  if (!usernameSelector) {\n")
	builder.WriteString("    await ctx.log.info(\"demo login username input not found; continuing without login\", { nodeId: \"login\" });\n")
	builder.WriteString("    return;\n")
	builder.WriteString("  }\n")
	builder.WriteString("  await ctx.page.fill(usernameSelector, await ctx.secrets.get(cascadeDemoUsernameSecretRef), { timeout: 2500 });\n")
	builder.WriteString("  await ctx.page.fill(passwordSelector, await ctx.secrets.get(cascadeDemoPasswordSecretRef), { timeout: 2500 });\n")
	builder.WriteString("  const submitSelector = await cascadeResolveSelector(ctx, \"login_submit\", submitSelectors, 2500).catch(() => \"\");\n")
	builder.WriteString("  if (submitSelector) await ctx.page.click(submitSelector, { timeout: 3000 });\n")
	builder.WriteString("  await ctx.page.waitForLoadState(\"networkidle\", { timeout: 8000 }).catch(() => undefined);\n")
	builder.WriteString("  await ctx.page.waitForTimeout(1200);\n")
	builder.WriteString("}\n\n")
}

func writeScriptStep(builder *strings.Builder, doc *model.ExecutionScriptDocument, step model.ScriptStep) error {
	if step.NodeID == "" {
		return errors.New("script step node_id is required")
	}
	title := firstNonEmpty(step.Title, step.Narrative.Title, step.NodeID)
	timeoutMS := step.Action.TimeoutMS
	if timeoutMS <= 0 {
		timeoutMS = 10000
	}
	durationMS := step.Timing.DurationMS
	if durationMS <= 0 {
		durationMS = 1000
	}
	selector := scriptStepSelector(step)
	targetURL := firstNonEmpty(step.Action.Target.URL, step.PageTarget.URL)
	maskSelectors := uniqueStrings(append(append([]string{}, doc.SafetyPolicy.Redactions.MaskSelectors...), step.Capture.MaskSelectors...))
	actionType := step.Action.Type
	if businessActionNeedsExecutableSelector(actionType) && !selectorUsableForBusinessAction(selector) {
		actionType = model.GraphActionInspect
	}
	runtimeAdaptive := scriptStepIsRuntimeAdaptive(step)
	requireAdaptiveResolution := step.Blocking || isBusinessAction(actionType)

	builder.WriteString("\n")
	builder.WriteString("  await ctx.log.step(" + jsString(step.NodeID) + ", " + jsString(title) + ");\n")
	builder.WriteString("  await ctx.capture.mark(" + jsString(step.NodeID) + ", { order: " + fmt.Sprint(step.Order) + ", action: " + jsString(string(step.Action.Type)) + " });\n")
	if naturalPause := preActionPauseMS(actionType, durationMS); naturalPause > 0 {
		builder.WriteString("  await ctx.page.waitForTimeout(" + fmt.Sprint(naturalPause) + ");\n")
	}

	switch actionType {
	case model.GraphActionNavigate:
		urlValue := firstNonEmpty(targetURL, doc.RecordingRunSpec.BaseURL)
		if urlValue == "" {
			builder.WriteString("  await ctx.log.info(\"navigate step has no URL; using current page\", { nodeId: " + jsString(step.NodeID) + " });\n")
			break
		}
		waitUntil := firstNonEmpty(step.Action.WaitUntil, "networkidle")
		builder.WriteString("  await ctx.page.goto(" + jsString(urlValue) + ", { waitUntil: " + jsString(waitUntil) + ", timeout: " + fmt.Sprint(timeoutMS) + " });\n")
		builder.WriteString("  await ctx.page.waitForLoadState(" + jsString(waitUntil) + ", { timeout: " + fmt.Sprint(timeoutMS) + " });\n")
		builder.WriteString("  await cascadeEnsureDemoLogin(ctx);\n")
	case model.GraphActionClick:
		if selector == "" {
			builder.WriteString("  await ctx.log.info(\"click step has no selector; recorded as manual inspection\", { nodeId: " + jsString(step.NodeID) + " });\n")
			break
		}
		candidates := scriptStepCandidateSelectors(step, selector)
		if runtimeAdaptive || len(candidates) > 1 {
			selectorVar := "selector_" + jsIdentifier(step.NodeID)
			if requireAdaptiveResolution {
				builder.WriteString("  const " + selectorVar + " = await cascadeResolveSelector(ctx, " + jsString(step.NodeID) + ", " + jsJSON(candidates) + ", " + fmt.Sprint(timeoutMS) + ");\n")
				builder.WriteString("  await ctx.page.click(" + selectorVar + ", { timeout: " + fmt.Sprint(timeoutMS) + " });\n")
			} else {
				builder.WriteString("  const " + selectorVar + " = await cascadeResolveSelector(ctx, " + jsString(step.NodeID) + ", " + jsJSON(candidates) + ", " + fmt.Sprint(timeoutMS) + ").catch(async (error) => { await ctx.log.info(\"adaptive selector unresolved; continuing with capture\", { nodeId: " + jsString(step.NodeID) + ", error: String(error).slice(0, 180) }); return \"\"; });\n")
				builder.WriteString("  if (" + selectorVar + ") await ctx.page.click(" + selectorVar + ", { timeout: " + fmt.Sprint(timeoutMS) + " }).catch((error) => ctx.log.info(\"adaptive click failed; continuing\", { nodeId: " + jsString(step.NodeID) + ", error: String(error).slice(0, 180) }));\n")
				builder.WriteString("  else await ctx.log.info(\"adaptive click skipped because no candidate matched\", { nodeId: " + jsString(step.NodeID) + " });\n")
			}
		} else {
			builder.WriteString("  await ctx.page.click(" + jsString(selector) + ", { timeout: " + fmt.Sprint(timeoutMS) + " });\n")
		}
		builder.WriteString("  await ctx.page.waitForLoadState(\"networkidle\", { timeout: " + fmt.Sprint(minInt(timeoutMS, 6000)) + " }).catch(() => ctx.log.info(\"page did not reach networkidle after click; continuing with capture\", { nodeId: " + jsString(step.NodeID) + " }));\n")
	case model.GraphActionFill:
		if selector == "" {
			builder.WriteString("  await ctx.log.info(\"fill step has no selector; recorded as manual inspection\", { nodeId: " + jsString(step.NodeID) + " });\n")
			break
		}
		valueExpr, err := scriptInputExpression(step)
		if err != nil {
			return err
		}
		candidates := scriptStepCandidateSelectors(step, selector)
		if runtimeAdaptive || len(candidates) > 1 {
			selectorVar := "selector_" + jsIdentifier(step.NodeID)
			if requireAdaptiveResolution {
				builder.WriteString("  const " + selectorVar + " = await cascadeResolveSelector(ctx, " + jsString(step.NodeID) + ", " + jsJSON(candidates) + ", " + fmt.Sprint(timeoutMS) + ");\n")
				builder.WriteString("  await ctx.page.fill(" + selectorVar + ", " + valueExpr + ", { timeout: " + fmt.Sprint(timeoutMS) + " });\n")
			} else {
				builder.WriteString("  const " + selectorVar + " = await cascadeResolveSelector(ctx, " + jsString(step.NodeID) + ", " + jsJSON(candidates) + ", " + fmt.Sprint(timeoutMS) + ").catch(async (error) => { await ctx.log.info(\"adaptive fill target unresolved; continuing\", { nodeId: " + jsString(step.NodeID) + ", error: String(error).slice(0, 180) }); return \"\"; });\n")
				builder.WriteString("  if (" + selectorVar + ") await ctx.page.fill(" + selectorVar + ", " + valueExpr + ", { timeout: " + fmt.Sprint(timeoutMS) + " }).catch((error) => ctx.log.info(\"adaptive fill failed; continuing\", { nodeId: " + jsString(step.NodeID) + ", error: String(error).slice(0, 180) }));\n")
				builder.WriteString("  else await ctx.log.info(\"adaptive fill skipped because no candidate matched\", { nodeId: " + jsString(step.NodeID) + " });\n")
			}
		} else {
			builder.WriteString("  await ctx.page.fill(" + jsString(selector) + ", " + valueExpr + ", { timeout: " + fmt.Sprint(timeoutMS) + " });\n")
		}
		builder.WriteString("  await ctx.page.waitForTimeout(800);\n")
	case model.GraphActionSelect:
		if selector == "" {
			builder.WriteString("  await ctx.log.info(\"select step has no selector; recorded as manual inspection\", { nodeId: " + jsString(step.NodeID) + " });\n")
			break
		}
		valueExpr, err := scriptInputExpression(step)
		if err != nil {
			return err
		}
		candidates := scriptStepCandidateSelectors(step, selector)
		if runtimeAdaptive || len(candidates) > 1 {
			selectorVar := "selector_" + jsIdentifier(step.NodeID)
			if requireAdaptiveResolution {
				builder.WriteString("  const " + selectorVar + " = await cascadeResolveSelector(ctx, " + jsString(step.NodeID) + ", " + jsJSON(candidates) + ", " + fmt.Sprint(timeoutMS) + ");\n")
				builder.WriteString("  await ctx.page.selectOption(" + selectorVar + ", " + valueExpr + ", { timeout: " + fmt.Sprint(timeoutMS) + " });\n")
			} else {
				builder.WriteString("  const " + selectorVar + " = await cascadeResolveSelector(ctx, " + jsString(step.NodeID) + ", " + jsJSON(candidates) + ", " + fmt.Sprint(timeoutMS) + ").catch(async (error) => { await ctx.log.info(\"adaptive select target unresolved; continuing\", { nodeId: " + jsString(step.NodeID) + ", error: String(error).slice(0, 180) }); return \"\"; });\n")
				builder.WriteString("  if (" + selectorVar + ") await ctx.page.selectOption(" + selectorVar + ", " + valueExpr + ", { timeout: " + fmt.Sprint(timeoutMS) + " }).catch((error) => ctx.log.info(\"adaptive select failed; continuing\", { nodeId: " + jsString(step.NodeID) + ", error: String(error).slice(0, 180) }));\n")
				builder.WriteString("  else await ctx.log.info(\"adaptive select skipped because no candidate matched\", { nodeId: " + jsString(step.NodeID) + " });\n")
			}
		} else {
			builder.WriteString("  await ctx.page.selectOption(" + jsString(selector) + ", " + valueExpr + ", { timeout: " + fmt.Sprint(timeoutMS) + " });\n")
		}
		builder.WriteString("  await ctx.page.waitForTimeout(800);\n")
	case model.GraphActionUpload:
		if selector == "" {
			builder.WriteString("  await ctx.log.info(\"upload step has no selector; recorded as manual inspection\", { nodeId: " + jsString(step.NodeID) + " });\n")
			break
		}
		fileRef := firstNonEmpty(step.Action.InputRef, step.Action.SecretRef)
		if fileRef == "" {
			builder.WriteString("  await ctx.log.info(\"upload step has no file ref; skipped file selection\", { nodeId: " + jsString(step.NodeID) + " });\n")
			break
		}
		candidates := scriptStepCandidateSelectors(step, selector)
		if runtimeAdaptive || len(candidates) > 1 {
			selectorVar := "selector_" + jsIdentifier(step.NodeID)
			if requireAdaptiveResolution {
				builder.WriteString("  const " + selectorVar + " = await cascadeResolveSelector(ctx, " + jsString(step.NodeID) + ", " + jsJSON(candidates) + ", " + fmt.Sprint(timeoutMS) + ");\n")
				builder.WriteString("  await ctx.page.setInputFiles(" + selectorVar + ", await ctx.secrets.getFile(" + jsString(fileRef) + "));\n")
			} else {
				builder.WriteString("  const " + selectorVar + " = await cascadeResolveSelector(ctx, " + jsString(step.NodeID) + ", " + jsJSON(candidates) + ", " + fmt.Sprint(timeoutMS) + ").catch(async (error) => { await ctx.log.info(\"adaptive upload target unresolved; continuing\", { nodeId: " + jsString(step.NodeID) + ", error: String(error).slice(0, 180) }); return \"\"; });\n")
				builder.WriteString("  if (" + selectorVar + ") await ctx.page.setInputFiles(" + selectorVar + ", await ctx.secrets.getFile(" + jsString(fileRef) + ")).catch((error) => ctx.log.info(\"adaptive upload failed; continuing\", { nodeId: " + jsString(step.NodeID) + ", error: String(error).slice(0, 180) }));\n")
				builder.WriteString("  else await ctx.log.info(\"adaptive upload skipped because no candidate matched\", { nodeId: " + jsString(step.NodeID) + " });\n")
			}
		} else {
			builder.WriteString("  await ctx.page.setInputFiles(" + jsString(selector) + ", await ctx.secrets.getFile(" + jsString(fileRef) + "));\n")
		}
		builder.WriteString("  await ctx.page.waitForTimeout(1000);\n")
	case model.GraphActionPress:
		keys := approvedKeyboardKeys(step.Action.Parameters)
		if len(keys) == 0 {
			return fmt.Errorf("press step %q has no approved keyboard keys", step.NodeID)
		}
		for _, key := range keys {
			builder.WriteString("  await ctx.page.keyboard.press(" + jsString(key) + ");\n")
			builder.WriteString("  await ctx.page.waitForTimeout(350);\n")
		}
	case model.GraphActionGesture:
		builder.WriteString("  await ctx.log.info(\"bounded gesture is delegated to browser-agent runtime\", { nodeId: " + jsString(step.NodeID) + " });\n")
	case model.GraphActionWait:
		if selector != "" {
			builder.WriteString("  await ctx.page.locator(" + jsString(selector) + ").waitFor({ timeout: " + fmt.Sprint(timeoutMS) + " });\n")
		} else {
			builder.WriteString("  await ctx.page.waitForTimeout(" + fmt.Sprint(durationMS) + ");\n")
		}
	case model.GraphActionAssert:
		builder.WriteString("  await ctx.log.info(\"assert step validates the current page state\", { nodeId: " + jsString(step.NodeID) + " });\n")
	case model.GraphActionInspect:
		builder.WriteString("  await ctx.log.info(\"inspect step uses the current page state\", { nodeId: " + jsString(step.NodeID) + " });\n")
		if selector != "" {
			softTimeoutMS := minInt(timeoutMS, 3000)
			builder.WriteString("  await ctx.page.locator(" + jsString(selector) + ").waitFor({ timeout: " + fmt.Sprint(softTimeoutMS) + " }).catch(() => ctx.log.info(\"inspect selector not visible; continuing with viewport capture\", { nodeId: " + jsString(step.NodeID) + ", selector: " + jsString(selector) + " }));\n")
		}
	case model.GraphActionAPICall:
		builder.WriteString("  await ctx.assert.apiCall(" + jsString(step.NodeID) + ", { parameters: " + jsJSON(step.Action.Parameters) + ", timeout: " + fmt.Sprint(timeoutMS) + " });\n")
	default:
		return fmt.Errorf("unsupported graph action type %q", step.Action.Type)
	}

	writeStepAssertions(builder, step, actionType, selector, targetURL, timeoutMS)
	if step.Capture.Screenshot {
		builder.WriteString("  await ctx.page.waitForLoadState(\"networkidle\", { timeout: " + fmt.Sprint(minInt(timeoutMS, 6000)) + " }).catch(() => undefined);\n")
		builder.WriteString("  await ctx.page.waitForTimeout(1000);\n")
		builder.WriteString("  await ctx.capture.screenshot(" + jsJSON(captureScreenshotOptions(step, selector, maskSelectors)) + ");\n")
	}
	if step.Capture.Video {
		builder.WriteString("  await ctx.capture.mark(" + jsString(step.NodeID+":video") + ", { durationMs: " + fmt.Sprint(durationMS) + " });\n")
	}
	if hold := boundedHoldMS(step.Timing.HoldAfterMS, durationMS); hold > 0 {
		builder.WriteString("  await ctx.page.waitForTimeout(" + fmt.Sprint(hold) + ");\n")
	}
	builder.WriteString("  stepResults.push({ nodeId: " + jsString(step.NodeID) + ", status: \"passed\", durationMs: " + fmt.Sprint(durationMS) + " });\n")
	return nil
}

func captureScreenshotOptions(step model.ScriptStep, selector string, maskSelectors []string) map[string]any {
	options := map[string]any{
		"nodeId":        step.NodeID,
		"selector":      firstNonEmpty(step.Capture.FocusSelector, selector),
		"maskSelectors": maskSelectors,
		"zoom":          step.Capture.Zoom,
		"callout":       step.Capture.Callout,
	}
	if step.Capture.Scope != "" {
		options["scope"] = step.Capture.Scope
	}
	if step.Capture.FullPage {
		options["full_page"] = true
	}
	return options
}

func writeStepAssertions(builder *strings.Builder, step model.ScriptStep, actionType model.GraphActionType, selector string, targetURL string, timeoutMS int) {
	if actionType == model.GraphActionInspect || actionType == model.GraphActionWait {
		builder.WriteString("  await ctx.log.info(\"observation step validation is non-blocking\", { nodeId: " + jsString(step.NodeID) + " });\n")
		return
	}
	if scriptStepIsRuntimeAdaptive(step) {
		builder.WriteString("  await ctx.log.info(\"runtime adaptive step validation is diagnostic-only\", { nodeId: " + jsString(step.NodeID) + " });\n")
		return
	}
	expected := firstNonEmpty(step.ExpectedOutcome, step.Narrative.Caption, step.Narrative.Voiceover)
	if expected != "" {
		if selector == "" || selectorUsableForBlockingAssertion(selector) {
			builder.WriteString("  await ctx.assert.step(" + jsString(step.NodeID) + ", " + jsString(expected) + ", { selector: " + jsString(selector) + ", url: " + jsString(targetURL) + ", timeout: " + fmt.Sprint(timeoutMS) + " });\n")
		} else {
			builder.WriteString("  await ctx.log.info(\"skip blocking assert.step for low-quality selector\", { nodeId: " + jsString(step.NodeID) + ", selector: " + jsString(selector) + " });\n")
		}
	}
	for _, validation := range step.Validations {
		if !validation.Required || validation.Severity != "blocking" {
			continue
		}
		validationSelector := firstNonEmpty(validation.Target.Selector, selector)
		if validationSelector != "" && !selectorUsableForBlockingAssertion(validationSelector) {
			builder.WriteString("  await ctx.log.info(\"skip blocking validation for low-quality selector\", { nodeId: " + jsString(step.NodeID) + ", validationId: " + jsString(validation.ID) + ", selector: " + jsString(validationSelector) + " });\n")
			continue
		}
		validationExpected := fmt.Sprint(validation.Expected)
		if validation.Assertion != "" {
			validationExpected = validation.Assertion
		}
		if validationSelector != "" && validationExpected != "" && validationExpected != "<nil>" {
			builder.WriteString("  await ctx.assert.text(" + jsString(validationSelector) + ", " + jsString(validationExpected) + ", { nodeId: " + jsString(step.NodeID) + ", validationId: " + jsString(validation.ID) + ", timeout: " + fmt.Sprint(timeoutMS) + " });\n")
		} else if validationSelector != "" {
			builder.WriteString("  await ctx.assert.visible(" + jsString(validationSelector) + ", { nodeId: " + jsString(step.NodeID) + ", validationId: " + jsString(validation.ID) + ", timeout: " + fmt.Sprint(timeoutMS) + " });\n")
		}
		if validation.Target.URL != "" {
			builder.WriteString("  await ctx.assert.url(" + jsString(validation.Target.URL) + ", { nodeId: " + jsString(step.NodeID) + ", validationId: " + jsString(validation.ID) + ", timeout: " + fmt.Sprint(timeoutMS) + " });\n")
		}
	}
}

func scriptStepIsRuntimeAdaptive(step model.ScriptStep) bool {
	if strings.Contains(strings.ToLower(strings.Join(stepNodeValidationKinds(step.Validations), " ")), "runtime_adaptive") {
		return true
	}
	for _, candidate := range step.Action.Target.SelectorAlternatives {
		if strings.Contains(strings.ToLower(candidate.Source), "runtime_adaptive") {
			return true
		}
	}
	for _, candidate := range step.PageTarget.SelectorAlternatives {
		if strings.Contains(strings.ToLower(candidate.Source), "runtime_adaptive") {
			return true
		}
	}
	return false
}

func stepNodeValidationKinds(validations []model.ValidationSpec) []string {
	kinds := make([]string, 0, len(validations))
	for _, validation := range validations {
		kinds = append(kinds, validation.Kind)
	}
	return kinds
}

func scriptInputExpression(step model.ScriptStep) (string, error) {
	if step.Action.SecretRef != "" {
		return "await ctx.secrets.get(" + jsString(step.Action.SecretRef) + ")", nil
	}
	if step.Action.InputRef != "" {
		return "await ctx.secrets.getInput(" + jsString(step.Action.InputRef) + ")", nil
	}
	if looksSensitiveLiteral(step.Action.Value) {
		return "", fmt.Errorf("step %s contains sensitive inline value; use secret_ref or input_ref", step.NodeID)
	}
	return jsString(step.Action.Value), nil
}

func scriptStepSelector(step model.ScriptStep) string {
	return bestSelectorValue(
		actionTargetTestIDSelector(step.Action.Target),
		bestSelectorCandidate(step.Action.Target.SelectorAlternatives),
		bestSelectorCandidate(step.PageTarget.SelectorAlternatives),
		step.Action.Target.Selector,
		step.PageTarget.Selector,
	)
}

func scriptStepCandidateSelectors(step model.ScriptStep, primary string) []string {
	candidates := []string{}
	add := func(value string) {
		value = strings.TrimSpace(value)
		if value == "" || selectorLooksGeneric(value) {
			return
		}
		for _, existing := range candidates {
			if normalizeSelector(existing) == normalizeSelector(value) {
				return
			}
		}
		candidates = append(candidates, value)
	}
	add(primary)
	add(actionTargetTestIDSelector(step.Action.Target))
	for _, candidate := range step.Action.Target.SelectorAlternatives {
		add(candidate.Value)
	}
	for _, candidate := range step.PageTarget.SelectorAlternatives {
		add(candidate.Value)
	}
	for _, label := range []string{step.Action.Target.Text, step.Action.Target.Label} {
		for _, selector := range adaptiveSelectorsForScriptLabel(label) {
			add(selector)
		}
	}
	return candidates
}

func adaptiveSelectorsForScriptLabel(label string) []string {
	label = strings.TrimSpace(label)
	if label == "" {
		return nil
	}
	escaped := strings.ReplaceAll(strings.ReplaceAll(label, `\`, `\\`), `"`, `\"`)
	return []string{
		`button:has-text("` + escaped + `")`,
		`a:has-text("` + escaped + `")`,
		`[role="button"]:has-text("` + escaped + `")`,
		`[aria-label*="` + escaped + `"]`,
		`text=` + label,
	}
}

func demoCredentialSecretRefs(doc *model.ExecutionScriptDocument) (string, string) {
	if doc == nil || doc.WorkflowGraph == nil {
		return "", ""
	}
	username := ""
	password := ""
	for _, variable := range doc.WorkflowGraph.Variables {
		switch variable.Name {
		case "demo_username":
			username = firstNonEmpty(username, variable.SecretRef)
		case "demo_password":
			password = firstNonEmpty(password, variable.SecretRef)
		}
	}
	return username, password
}

func selectorCandidateValue(candidates []model.SelectorCandidate) string {
	for _, candidate := range candidates {
		if candidate.Value != "" {
			return candidate.Value
		}
	}
	return ""
}

func boundedHoldMS(holdMS int, durationMS int) int {
	if holdMS > 0 {
		if holdMS > 10000 {
			return 10000
		}
		return holdMS
	}
	if durationMS <= 0 {
		return 0
	}
	if durationMS > 10000 {
		return 10000
	}
	return durationMS
}

func preActionPauseMS(actionType model.GraphActionType, durationMS int) int {
	if durationMS < 10000 {
		return 0
	}
	switch actionType {
	case model.GraphActionClick, model.GraphActionFill, model.GraphActionSelect, model.GraphActionUpload, model.GraphActionPress, model.GraphActionGesture:
		return 1200
	case model.GraphActionInspect, model.GraphActionWait:
		return 0
	default:
		return 800
	}
}

func jsString(value string) string {
	return strconv.Quote(value)
}

func jsBool(value bool) string {
	if value {
		return "true"
	}
	return "false"
}

func jsJSON(value any) string {
	data, err := json.Marshal(value)
	if err != nil {
		return "null"
	}
	return string(data)
}

func jsIdentifier(value string) string {
	value = strings.TrimSpace(value)
	if value == "" {
		return "value"
	}
	var builder strings.Builder
	for i, r := range value {
		allowed := (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || r == '_'
		if i > 0 {
			allowed = allowed || (r >= '0' && r <= '9')
		}
		if allowed {
			builder.WriteRune(r)
		} else {
			builder.WriteByte('_')
		}
	}
	out := strings.Trim(builder.String(), "_")
	if out == "" {
		return "value"
	}
	return out
}

func looksSensitiveLiteral(value string) bool {
	lower := strings.ToLower(value)
	for _, token := range []string{"password", "passwd", "secret", "api_key", "apikey", "private key", "bearer ", "sk-"} {
		if strings.Contains(lower, token) {
			return true
		}
	}
	return strings.Contains(value, "BEGIN PRIVATE KEY")
}

func actionTargetTestIDSelector(target model.ActionTarget) string {
	if target.TestID == "" {
		return ""
	}
	return "[data-testid='" + target.TestID + "']"
}
